### ISSUE TITLE
IndexError bei Vibrationsmessung Y-Achse

### ISSUE THREAD

**Issue by jofland** [cryd-s/klipper_scripts#6]
Bei der Vibrationsmessung der Y-Achse bekomme ich ständig folgenden Stacktrace:

```
idx_below = np.where(psd[:max_power_index] <= half_power)[0][-1]
IndexError: index -1 is out of bounds for axis 0 with size 0

motor_fr, motor_zeta, motor_max_power_index = compute_mechanical_parameters(motor_vibration_power, freqs)
File "/home/jens/klippain_shaketune/K-ShakeTune/scripts/common_func.py", line 81, in compute_mechanical_parameters

create_vibrations_graph(axis_name=options.axis_name, accel=options.accel_used, chip_name=options.chip_name, keep_csv=options.keep_csv)
File "/home/jens/klippain_shaketune/K-ShakeTune/scripts/is_workflow.py", line 165, in create_vibrations_graph
fig = vibrations_calibration(lognames, KLIPPER_FOLDER, axis_name, accel)
File "/home/jens/klippain_shaketune/K-ShakeTune/scripts/graph_vibrations.py", line 382, in vibrations_calibration

main()
File "/home/jens/klippain_shaketune/K-ShakeTune/scripts/is_workflow.py", line 292, in main

Vibrations peaks detected: 3 @ 64.0, 70.0, 90.0 mm/s (avoid setting a speed near these values in your slicer print profile)
Traceback (most recent call last):
File "/home/jens/klippain_shaketune/K-ShakeTune/scripts/is_workflow.py", line 303, in
Running Command {shaketune}...:

```
Makro Einstellungen Vibrations Calibration:

- SIZE 80
- DIRECTION Y
- Z_HEIGHT 20
- MIN_SPEED 50
- MAX_Speed 230
- SPEED_INCREMT 2 (oder 5)
- TRAVEL_SPEED 200
- ACCEL 3000
- ACCEL_CHIP adxl345
- KEEP_IN_RESULTS 3
- KEEP_CSV True

printer.cfg
```
[adxl345]
cs_pin: rpi:None
axes_map: x,-z,y #die Ausrichtung ist abhängig vom ADXL mount.

[resonance_tester]
accel_chip: adxl345
probe_points:
    117.5,117.5,20   #beziehungsweise die Koordinaten für die Mitte des Druckbetts

[mcu rpi]
serial: /tmp/klipper_host_mcu

[input_shaper]
shaper_freq_x: 61.8 # Mittenfrequenz für den X-Achsen-Filter
shaper_type_x: ei # Filtertyp für die X-Achse
shaper_freq_y: 65.8 # Mittenfrequenz für den Y-Achsen-Filter
shaper_type_y: ei # Filtertyp für die Y-Achse
damping_ratio_x: 0.044 # Dämpfungsverhältnis für die X-Achse
damping_ratio_y: 0.037 # Dämpfungsverhältnis für die Y-Achse

```

Version 3.0

Drucker Elegoo Neptune 3 Pro

Wenn ich mit ACCEL auf 1800 runter gehe und gleichzeitig Increment auf 5 setze, läuft die Messung *manchmal* fehlerfrei durch.

Ebenso fehlerfrei läuft es, wenn ich mit obigen Einstellungen X und Y messen lasse (ohne Sensor an X).

**Comment by jofland** [comment]
Ich habe jetzt noch ein paar Sachen umgestellt. Jetzt läuft das Tuning mit obigen Einstellungen fehlerfrei durch.
